'use strict';

module.exports = {
	'ENTERPRISE': {
		'UPLOAD': {
			'Request_Type*': 'requestType',
			'Purpose*': 'purpose',
			'Agency_Name*': 'agencyName',
			'Enterprise*': 'enterpriseName',
			'Customer_Transaction_ID': 'customerTransactionId',
			'Customer_Valuation_No': 'customerValuationNo',
			'Customer_Party_No': 'customerPartyNo',
			'Customer_Party_Name': 'customerPartyName',
			'User': 'user',
			'Request_Date': 'requestDate',
			'Asset_No': 'assetId',
			'Repo_Date': 'repoDate',
			'Asset_Type/Category*': 'category',
			'Make/Brand*': 'brand',
			'Model*': 'model',
			'Asset_Description': 'assetDescription',
			'Engine_No': 'engineNo',
			'Chassis_No': 'chassisNo',
			'Registration_No': 'registrationNo',
			'Invoice_Date': 'invoiceDate',
			'Yard_Parked': 'yardParked',
			'Country*': 'country',
			'State*': 'state',
			'Location*': 'city',
			'Contact_Person': 'contactPerson',
			'Contact_Person_Tel_No': 'contactPersonTelNo',
			'Distance_from_Customer_Office': 'disFromCustomerOffice'
		},
		'MODIFY': {
			'Unique_Control_No*': 'uniqueControlNo',
			'Request_Type*': 'requestType',
			'Purpose*': 'purpose',
			'Agency_Name*': 'agencyName',
			'Enterprise*': 'enterpriseName',
			'Customer_Transaction_ID': 'customerTransactionId',
			'Customer_Valuation_No': 'customerValuationNo',
			'Customer_Party_No': 'customerPartyNo',
			'Customer_Party_Name': 'customerPartyName',
			'User': 'user',
			'Request_Date': 'requestDate',
			'Asset_No': 'assetId',
			'Repo_Date': 'repoDate',
			'Asset_Type/Category*': 'category',
			'Make/Brand*': 'brand',
			'Model*': 'model',
			'Asset_Description': 'assetDescription',
			'Engine_No': 'engineNo',
			'Chassis_No': 'chassisNo',
			'Registration_No': 'registrationNo',
			'Invoice_Date': 'invoiceDate',
			'Yard_Parked': 'yardParked',
			'Country*': 'country',
			'State*': 'state',
			'Location*': 'city',
			'Contact_Person': 'contactPerson',
			'Contact_Person_Tel_No': 'contactPersonTelNo',
			'Distance_from_Customer_Office': 'disFromCustomerOffice'
		},
		'EXPORT': {
			'TRANSACTION': {},
			'INVOICE': {}
		}
	},
	'VALUATION_PARTNER': {
		'MODIFY': {
			'Unique_Control_No*': 'uniqueControlNo',
			'Report_Date': 'reportDate',
			'Report_No': 'reportNo',
			'Year_of_Manufacture': 'yearOfManufacturing',
			'HMR/KMR': 'hmr_kmr',
			'Assessed_Value': 'assessedValue',
			'Inspection_By': 'inspectionBy',
			'Physical_Condition': 'physicalCondition',
			'GPS_Installed': 'gpsInstalled',
			'GPS_Device_No': 'gpsDeviceNo',
			'IMIE_No': 'gpsIMEINo'
		}
	},
	'ASSETGROUP' : {
		'Valuer_Group_ID' : 'valuerGroupId' ,
		'Valuer_Asset_ID' : 'valuerAssetId' ,
		'Valuer_Name' : 'valuerName',
		'Valuer_Code'  : 'valuerCode',
		'ASSET_CATEGORY' : 'assetCategory',
		'Enterprise_Name' : 'enterpriseName',
		'Enterprise_ID': 'enterpriseId'
	},
	'TRANSACTION_EXPORT':{
		"Unique Control Number":{key:"uniqueControlNo",type:"string"},
		"Status":{key:"status",type:"string"},
		"Request Type":{key:"requestType",type:"string"},
		"Purpose":{key:"purpose",type:"string"},
		"Agency Name":{key:"agency.name",type:"string"},
		"Enterprise":{key:"enterprise.enterpriseId",type:"string"},
		"Customer Transaction ID":{key:"customerTransactionId",type:"string"},
		"Customer Valuation No":{key:"customerValuationNo",type:"string"},
		"Customer Party No":{key:"customerPartyNor",type:"string"},
		"Customer Party Name":{key:"customerPartyName",type:"string"},
		"User":{key:"userName",type:"string"},
		"Request Date":{key:"requestDate",type:"string"},
		"Asset No":{key:"assetId",type:"string"},
		"Repo. Date":{key:"repoDate",type:"string"},
		"Make":{key:"Brand",type:"string"},
		"Model":{key:"model",type:"string"},
		"Asset Description":{key:"assetDescription",type:"string"},
		"Asset Type":{key:"assetType",type:"string"},
		"Engine No":{key:"engineNo",type:"string"},
		"Chassis No":{key:"chassisNo",type:"string"},
		"Regn No":{key:"registrationNo",type:"string"},
		"Invoice Date":{key:"invoiceDate",type:"string"},
		"Yard Parked":{key:"yardParked",type:"string"},
		"Location":{key:"city",type:"string"},
		"State":{key:"state",type:"string"},
		"Country":{key:"country",type:"string"},
		"Contact Person":{key:"contactPerson",type:"string"},
		"Contact Person TelNo":{key:"contactPersonTelNo",type:"string"},
		"Distance From Customer Office":{key:"disFromCustomerOffice",type:"string"},
		"Report No":{key:"reportNo",type:"string"},
		"Report Date":{key:"reportDate",type:"string"},
		"Year of Manufacture":{key:"yearOfManufacturing",type:"string"},
		"HMR / KMR":{key:"hmr_kmr",type:"string"},
		"Assessed Value":{key:"assessedValue",type:"string"},
		"Inspection By":{key:"inspectionBy",type:"string"},
		"Physical Condition":{key:"physicalCondition",type:"string"},
		"GPS Installed":{key:"gpsInstalled",type:"boolean"},
		"IMIE No":{key:"gpsIMEINo",type:"string"},
		"GPS Device No":{key:"gpsDeviceNo",type:"string"},
		"Asset Image General":{key:"generalImage.filename",type:"string"},
		"Asset Image Engine":{key:"engineImage.filename",type:"string"},
		"Asset Image Hydraulic":{key:"hydraulicImage.filename",type:"string"},
		"Asset Image Cabin":{key:"cabinImage.filename",type:"string"},
		"Asset Image Under-Carriage / Tyre":{key:"underCarriage.filename",type:"string"},
		"Asset Image Others":{key:"otherImage.filename",type:"string"},
		"Valuation Report":{key:"valuationReport.filename",type:"string"},
		"Invoiced Date":{key:"invoiceDate",type:"string",allowedRoles:['admin']},
		"Invoice No":{key:"invoiceNo",type:"string",allowedRoles:['admin']},
		"Payment Received":{key:"paymentReceived",type:"boolean",allowedRoles:['admin']},
		"Payment Made to Agency":{key:"paymentMade",type:"boolean",allowedRoles:['admin']}
	},
	'INVOICE_EXPORT':{
		"Unique Invoive Number":{key:"invoiceNo"},
		"Request Type":{key:"requestType"},
		"Enterprise Name":{key : "enterprise.enterpriseId"},
		"Enterprise Contact No":{key:"enterprise.mobile"},
		"Valuation Partner Name":{key:"agency.name"},
		"Valuation Partner Contact No":{key:"agency.mobile"},
		"Invoice Amount":{key:"invoiceAmount"},
		"Invoice Date":{key:"createdAt"},
		"Payment Received":{key:"paymentReceived",type:'boolean',allowedRoles:['admin']},
		"Payment Made":{key:"paymentMade",type:'boolean',allowedRoles:['admin']},
	},
	'EXPORT_PAYMENT':{
		"Unique Invoive Number":{key:"invoiceNo"},
		"Request Type":{key:"requestType"},
		"Enterprise Name":{key:"enterpriseName"},
		"Enterprise Contact No":{key:"enterpriseContactNo"},
		"Valuation Partner Name":{key:"valuationPartnerName"},
		"Valuation Partner Contact No":{key:"valuationPartnerContactNo"},
		"Bank Name":{key:"bankName"},
		"Branch Name":{key:"branchName"},
		"Cheque No":{key:"chequeNo"},
		"Cheque Date":{key:"chequeDate"},
		"Cheque Value":{key:"chequeValue"},
		"Deducted TDS":{key:"deductedTds"}
	}
}