'use strict';

var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

var timestamp=require('unix-timestamp');

var AuctionMasterSchema = new Schema({
	name:String,
	startDate:Date,
	auctionId:String,
	endDate:Date,
	auctionOwner: String,
	auctionOwnerMobile:String,
	insStartDate: Date,
	insEndDate: Date,
	regEndDate: Date,
	city: String,
	state: String,
	auctionAddr: String,
	auctionType: String,
	regCharges : Number,
	docType:String,
	docName: String,
	groupId:String,
	createdAt: {type:Date,default:Date.now},
	updatedAt: {type:Date,default:Date.now},
});

module.exports = mongoose.model('AuctionMaster', AuctionMasterSchema);


/*db.auctionmasters.insert([{
	name:'redisgo',
	startDate:Date,
	auctionId:'15316',
	endDate:Date,
	auctionOwner:'Awasthi',
	insStartDate: Date,
	insEndDate: Date,
	regEndDate: Date,
	city: 'kolkata',
	state: 'West Bengal',
	auctionAddr: 'Park lane',
	auctionType:'trucks',
	regCharges : 8500,
	docType:String,
	docName: String,
	groupId:String,
	createdAt: {type:Date,default:Date.now},
	updatedAt: {type:Date,default:Date.now}
},
{
	name:'grandi10',
	startDate:Date,
	auctionId:'15317',
	endDate:Date,
	auctionOwner:'Siddharth',
	insStartDate: Date,
	insEndDate: Date,
	regEndDate: Date,
	city: 'Noida',
	state: 'UP',
	auctionAddr: 'sector 18',
	auctionType:'cranes',
	regCharges : 7000,
	docType:String,
	docName: String,
	groupId:String,
	createdAt: {type:Date,default:Date.now},
	updatedAt: {type:Date,default:Date.now}
},
{
	name:'polo',
	startDate:Date,
	auctionId:'15318',
	endDate:Date,
	auctionOwner:'Bhardwaj',
	insStartDate: Date,
	insEndDate: Date,
	regEndDate: Date,
	city: 'Gurgaon',
	state: 'Haryana',
	auctionAddr: 'sector 26',
	auctionType:'cars',
	regCharges : 7500,
	docType:String,
	docName: String,
	groupId:String,
	createdAt: {type:Date,default:Date.now},
	updatedAt: {type:Date,default:Date.now}
},
{
	name:'Baleno',
	startDate:Date,
	auctionId:'15319',
	endDate:Date,
	auctionOwner:'Suresh',
	insStartDate: Date,
	insEndDate: Date,
	regEndDate: Date,
	city: 'Agra',
	state: 'UP',
	auctionAddr: 'Taj Circle',
	auctionType:'hatchbacks',
	regCharges : 6500,
	docType:String,
	docName: String,
	groupId:String,
	createdAt: {type:Date,default:Date.now},
	updatedAt: {type:Date,default:Date.now}
},
{
	name:'Swift',
	startDate:Date,
	auctionId:'15320',
	endDate:Date,
	auctionOwner:'Sushant',
	insStartDate: Date,
	insEndDate: Date,
	regEndDate: Date,
	city: 'Bangalore',
	state: 'Karnataka',
	auctionAddr: 'Central Market',
	auctionType:'Small Cars',
	regCharges : 7500,
	docType:String,
	docName: String,
	groupId:String,
	createdAt: {type:Date,default:Date.now},
	updatedAt: {type:Date,default:Date.now}
},
{
	name:'Etios',
	startDate:Date,
	auctionId:'15321',
	endDate:Date,
	auctionOwner:'Firoz',
	insStartDate: Date,
	insEndDate: Date,
	regEndDate: Date,
	city: 'Chennai',
	state: 'Tamil Nadu',
	auctionAddr: 'Morgan Street',
	auctionType:'globalCars',
	regCharges : 8500,
	docType:String,
	docName: String,
	groupId:String,
	createdAt: {type:Date,default:Date.now},
	updatedAt: {type:Date,default:Date.now}
},
{
	name:'Liva',
	startDate:Date,
	auctionId:'15322',
	endDate:Date,
	auctionOwner:'Siddhesh',
	insStartDate: Date,
	insEndDate: Date,
	regEndDate: Date,
	city: 'Auli',
	state: 'Himachal',
	auctionAddr: 'Mall Road',
	auctionType:'lifters',
	regCharges : 9000,
	docType:'',
	docName: '',
	groupId:'',
	createdAt: {type:Date,default:Date.now},
	updatedAt: {type:Date,default:Date.now}
},
{
	name:'Ecosport',
	startDate:Date,
	auctionId:'15323',
	endDate:Date,
	auctionOwner:'Siddharth',
	insStartDate: Date,
	insEndDate: Date,
	regEndDate: Date,
	city: 'Shimla',
	state: 'Himachal',
	auctionAddr: 'Mall Road',
	auctionType:'MUV',
	regCharges : 8000,
	docType:'',
	docName: '',
	groupId:'',
	
}])*/